\c recipes_dev

INSERT INTO 
recipes(name, photo, type, cuisine, is_healthy, is_vegan, difficulty, ingredients, description, cookingTime)
VALUES
('Peanut butter & jelly sandwich','https://unsplash.com/photos/1i1zPbkQJNg','Snack', 'American',TRUE, TRUE, 'easy','peanut butter, jelly, bread', 'americas favorite snack'),
('Chorizo tacos','https://unsplash.com/photos/meQnwalVPyc','Lunch','Mexican',FALSE, FALSE, 'moderate','Chorizo sausage link(casing removed and meat crumbled), chipole peppers, corn tortillas, chopped onions, chopped cilantro','These chorizo tacos use just 5 ingredients and taste amazing.'),
('lumpia ','https://unsplash.com/photos/UkudQyyeovs','Snack', 'Filipino', FALSE, FALSE, 'moderate','vegetable oil, lumpia wrappers, ground pork, chopped onions, crushed garlic, minced carrots, chopped green onions, sliced cabbage, cilantro, salt, black pepper, garlic powder, soy sauce,','Lumpia are fried spring rolls that are found in Filipino and Indonesian cuisines'),
('Apple Strawberry Banana Smoothie','https://unsplash.com/photos/09v10GvEPr8', 'breakfast','N/A', TRUE, TRUE, 'easy','Almond Milk, Apple, Strawberry, Bananas, Greek Yogurt','Start your day off right with this quick and nutritious apple smoothie, ready in minutes. This breakfast smoothie has a nice combination of fruit and is slightly sweet, creamy, and satisfying.'),
('Lasagna','https://unsplash.com/photos/fF2o9WpkGhU','dinner', 'Italian', FALSE, FALSE, 'moderate', 'Sweet Italian Sausage, Lean Ground beef, Minced Onions, Crushed Garlic, Canned Crushed Tomatoes, Canned Tomato Sauce, Canned Tomato Paste, Water, White Sugar, Fresh Parsley, Dried Basil, Italian Season, Salt, Black Pepper, Fennel Seeds, Lasagna Noodles, Egg, Ricotta Cheese, Mozzarella Cheese, Parmesan Cheese','This lasagna recipe takes a little work, but it is so satisfying and filling that its worth it!'),
('Chicken Noodle Soup', 'https://unsplash.com/photos/vwnRw_r4kh4',  'Soup', 'American', TRUE, FALSE, 'Easy', 'Butter, Onion, Celery, Carrot, Can Chicken Broth, Can Vegetable Broth, Cooked Chicken, Egg Noodles, Dried Basil, Dried Oregano, Salt, Pepper','A chicken noodle soup recipe that is a very easy, very good substitute for when you dont have time to make your soup totally from scratch'),
('Fried Oreos', 'https://unsplash.com/photos/fcrx_cPicIs','Dessert','American',FALSE, TRUE,'Easy', 'Oreos, Pancake mix, Water, Powdered Sugar','Deep-fried Oreos are a carnival favorite. Oreos get dipped into pancake batter and fried — yummy!'),
('Roasted Potatoes','https://unsplash.com/photos/37oYY2wHu0Q', 'Side Dish', 'N/A', TRUE, TRUE, 'Easy','Gold Potatoes(Quartered), Olive Oil, Salt, Pepper, Rosemary','Roasted potatoes at their best — plain and simple!'),
('Buttermilk Pancakes','https://unsplash.com/photos/TkzdkVn1AyA','Breakfast','American', FALSE, TRUE,'Moderate', 'Flour, Baking soda, Baking Powder, Salt, Sugar, Melted Butter, Eggs, Buttermillk', 'A very light and fluffy pancake recipe that requires fresh buttermilk, but it is the best I ever made!')